# versão do composer
version: '3.1'

# criar volumes "dados"

volumes:
  dados:

# serviços
services:

  bd:
    image: postgres:9.6
    volumes:
      #volume dos dados
      - dados:/var/lib/postgresql/data
      # mapeamento da pasta scripts para  scripts
      - ./scripts:/scripts
      #convenção para mapeamento e execução de sript sql na inicialização do postgres
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment: 
      POSTGRES_USER: jhimmy
      POSTGRES_PASSWORD: ufam@2022  
  frontend:
    image: nginx:1.13
    #site; mapeamento da pasta web para a pasta do servidor nginx que serve a página  index.html
    volumes:
      - ./web:/usr/share/nginx/html/
    ports:
      - 80:80

  #gerenciador web de banco de dados 
  #adminer:
   # image: adminer
    #restart: always
    #ports:
     # - 8080:8080

  